<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '6',
    'typeid' => '0',
    'title' => '测试内容',
    'style' => '',
    'thumb' => 'http://www.pc.com/uploadfile/2018/1208/20181208010956491.png',
    'keywords' => '测试内容',
    'description' => '测试内容',
    'posids' => '0',
    'url' => 'http://www.pc.com/index.php?m=content&c=index&a=show&catid=6&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1544146738',
    'updatetime' => '1544245923',
    'hitsid' => 'c-1-1',
    'views' => '14',
    'yesterdayviews' => '8',
    'dayviews' => '6',
    'weekviews' => '14',
    'monthviews' => '14',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '6',
    'typeid' => '0',
    'title' => '测试内容1',
    'style' => '',
    'thumb' => 'http://www.pc.com/uploadfile/2018/1208/20181208035412830.png',
    'keywords' => '测试内容',
    'description' => '测试内容1',
    'posids' => '0',
    'url' => 'http://www.pc.com/index.php?m=content&c=index&a=show&catid=6&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1544175898',
    'updatetime' => '1544245849',
    'hitsid' => 'c-1-3',
    'views' => '4',
    'yesterdayviews' => '2',
    'dayviews' => '2',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
);
?>