<?php
$templatenames = array (
  'displaymgr.html' => '前台新楼市模版',
  'displaysearch.html' => '楼盘搜索模板',
  'footer.html' => '房产页底',
  'footer-i.html' => '房产首页页底',
  'frontmgr.html' => '房产信息管理模版',
  'header.html' => '房产头部模板',
  'housesearch.html' => '房产信息搜索模板',
  'index.html' => '房产首页模版',
  'infomgr.html' => '前台反产信息模版',
  'infopost.html' => '发布房产信息模版',
  'intermediary.html' => '房产中介信息',
  'listdisplay.html' => 'sdf',
  'listinfo.html' => '房产信息列表模版',
  'membertype.html' => '会员类型模版',
  'newhouse.html' => '楼盘内容页模版',
  'rentsearch.html' => '合租搜索模版',
  'showinfo.html' => '房产信息内容页模版',
  'tag_display_list.html' => '楼盘列表小标签模版',
  'tag_display_list-cat.html' => '',
  'tag_display_list-scrolldisplay.html' => '楼盘滚动小标签模版',
  'tag_display_list-top.html' => '首页中部推荐房产列表',
  'tag_house_list.html' => '房产信息列表模版',
  'tag_house_list-cat.html' => '',
  'tag_member_list.html' => '会员中介列表标签',
  'header-m.html' => 'ee',
  'web.html' => 'zhongjie',
  'web_list.html' => 'sf',
);
?>